### PR TITLE
Fix retrieval of current posts author id

### PR DESCRIPTION
**Pull request by tschortsch**

### CODE REVIEW

**Comment by tyxla** [comment]
Can you please describe the reason behind this change? It doesn't make it better in my opinion, as users would sometimes want to retrieve user meta from a user different from the current post's author.

**Comment by tschortsch** [comment]
The problem is that the used function get_the_author() doesn't return a WP_User object but the authors display name as a string (see https://codex.wordpress.org/Function_Reference/get_the_author). Since you're just using the ID I replaced it with the get_the_author_meta('ID') function.

**Comment by tyxla** [comment]
Makes sense. Merging. Thanks :+1:

**Comment by tschortsch** [comment]
No problem. Always glad to help to make this great plugin even better!

**Pull request merged**
